//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickDictForICC.Properties {
    using System;


    /// <summary>
    ///   强类型资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder 类自动生成的
    // 通过 ResGen 或 Visual Studio 之类的工具。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项) 或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public static class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickDictForICC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类的所有资源查找，覆盖当前线程的 CurrentUICulture
        ///   属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 英汉字典 的本地化字符串。
        /// </summary>
        public static string DictionaryWindow_Title {
            get {
                return ResourceManager.GetString("DictionaryWindow_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        public static string DictionaryWindow_LogoText {
            get {
                return ResourceManager.GetString("DictionaryWindow_LogoText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 英汉字典 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_Title {
            get {
                return ResourceManager.GetString("DictionaryPopup_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 输入单词查询 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_SearchPlaceholder {
            get {
                return ResourceManager.GetString("DictionaryPopup_SearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_ClearTooltip {
            get {
                return ResourceManager.GetString("DictionaryPopup_ClearTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向左滚动 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_ScrollLeftTooltip {
            get {
                return ResourceManager.GetString("DictionaryPopup_ScrollLeftTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向右滚动 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_ScrollRightTooltip {
            get {
                return ResourceManager.GetString("DictionaryPopup_ScrollRightTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请输入单词开始查询 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_EmptyHint {
            get {
                return ResourceManager.GetString("DictionaryPopup_EmptyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 词典加载中... 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_LoadingText {
            get {
                return ResourceManager.GetString("DictionaryPopup_LoadingText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 首次使用或词典较大时需要一些时间 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_LoadingDetail {
            get {
                return ResourceManager.GetString("DictionaryPopup_LoadingDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 退格 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_BackspaceTooltip {
            get {
                return ResourceManager.GetString("DictionaryPopup_BackspaceTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Space 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_SpaceButton {
            get {
                return ResourceManager.GetString("DictionaryPopup_SpaceButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        public static string DictionaryPopup_SearchButton {
            get {
                return ResourceManager.GetString("DictionaryPopup_SearchButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 词典服务尚未就绪 的本地化字符串。
        /// </summary>
        public static string Message_DictionaryServiceNotReady {
            get {
                return ResourceManager.GetString("Message_DictionaryServiceNotReady", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 词典正在加载中，请稍后再试 的本地化字符串。
        /// </summary>
        public static string Message_DictionaryLoading {
            get {
                return ResourceManager.GetString("Message_DictionaryLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未找到可用的词典文件。请在 QuickDict 设置中配置词典路径。 的本地化字符串。
        /// </summary>
        public static string Message_DictionaryNotConfigured {
            get {
                return ResourceManager.GetString("Message_DictionaryNotConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未找到 &quot;{0}&quot; 的释义 的本地化字符串。
        /// </summary>
        public static string Message_WordNotFound_Format {
            get {
                return ResourceManager.GetString("Message_WordNotFound_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 释义 的本地化字符串。
        /// </summary>
        public static string ResultTab_Definition {
            get {
                return ResourceManager.GetString("ResultTab_Definition", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 词组 的本地化字符串。
        /// </summary>
        public static string ResultTab_Phrases {
            get {
                return ResourceManager.GetString("ResultTab_Phrases", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 例句 的本地化字符串。
        /// </summary>
        public static string ResultTab_Sentences {
            get {
                return ResourceManager.GetString("ResultTab_Sentences", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 近义词 的本地化字符串。
        /// </summary>
        public static string ResultTab_Synonyms {
            get {
                return ResourceManager.GetString("ResultTab_Synonyms", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 朗读 的本地化字符串。
        /// </summary>
        public static string ResultView_SpeakTooltip {
            get {
                return ResourceManager.GetString("ResultView_SpeakTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂无词组 的本地化字符串。
        /// </summary>
        public static string ResultView_NoPhrases {
            get {
                return ResourceManager.GetString("ResultView_NoPhrases", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂无例句 的本地化字符串。
        /// </summary>
        public static string ResultView_NoSentences {
            get {
                return ResourceManager.GetString("ResultView_NoSentences", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂无近义词 的本地化字符串。
        /// </summary>
        public static string ResultView_NoSynonyms {
            get {
                return ResourceManager.GetString("ResultView_NoSynonyms", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 生成单词卡 的本地化字符串。
        /// </summary>
        public static string ResultView_GenerateCard {
            get {
                return ResourceManager.GetString("ResultView_GenerateCard", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法渲染 MDict HTML（WebView2 可能未安装）：{0} 的本地化字符串。
        /// </summary>
        public static string ResultView_HtmlRenderError_Format {
            get {
                return ResourceManager.GetString("ResultView_HtmlRenderError_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 朗读失败：{0} 的本地化字符串。
        /// </summary>
        public static string Message_SpeakFailed_Format {
            get {
                return ResourceManager.GetString("Message_SpeakFailed_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string MessageBox_Title_Notice {
            get {
                return ResourceManager.GetString("MessageBox_Title_Notice", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 生成单词卡功能即将上线 的本地化字符串。
        /// </summary>
        public static string Message_WordCardComingSoon {
            get {
                return ResourceManager.GetString("Message_WordCardComingSoon", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 QuickDict 设置 的本地化字符串。
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 配置词典路径与 TTS 发音选项。修改路径后需重启插件生效。 的本地化字符串。
        /// </summary>
        public static string Settings_Description {
            get {
                return ResourceManager.GetString("Settings_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 词典 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Dictionary {
            get {
                return ResourceManager.GetString("Settings_Section_Dictionary", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ECDICT 文件路径（ecdict.csv） 的本地化字符串。
        /// </summary>
        public static string Settings_EcDictPathLabel {
            get {
                return ResourceManager.GetString("Settings_EcDictPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 词典路径（.mdx） 的本地化字符串。
        /// </summary>
        public static string Settings_MDictPathLabel {
            get {
                return ResourceManager.GetString("Settings_MDictPathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 资源包路径（.mdd，可选） 的本地化字符串。
        /// </summary>
        public static string Settings_MDictResourcePathLabel {
            get {
                return ResourceManager.GetString("Settings_MDictResourcePathLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ECDICT 文件路径 的本地化字符串。
        /// </summary>
        public static string Settings_EcDictPathHeader {
            get {
                return ResourceManager.GetString("Settings_EcDictPathHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ecdict.csv 格式离线词库 的本地化字符串。
        /// </summary>
        public static string Settings_EcDictPathDescription {
            get {
                return ResourceManager.GetString("Settings_EcDictPathDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 词典路径 的本地化字符串。
        /// </summary>
        public static string Settings_MDictPathHeader {
            get {
                return ResourceManager.GetString("Settings_MDictPathHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 .mdx 格式 MDict 词典文件 的本地化字符串。
        /// </summary>
        public static string Settings_MDictPathDescription {
            get {
                return ResourceManager.GetString("Settings_MDictPathDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 资源包路径 的本地化字符串。
        /// </summary>
        public static string Settings_MDictResourcePathHeader {
            get {
                return ResourceManager.GetString("Settings_MDictResourcePathHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 .mdd 格式资源包，存放发音与图片等资源（可选） 的本地化字符串。
        /// </summary>
        public static string Settings_MDictResourcePathDescription {
            get {
                return ResourceManager.GetString("Settings_MDictResourcePathDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 浏览... 的本地化字符串。
        /// </summary>
        public static string Settings_BrowseButton {
            get {
                return ResourceManager.GetString("Settings_BrowseButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 语音朗读（TTS） 的本地化字符串。
        /// </summary>
        public static string Settings_Section_Tts {
            get {
                return ResourceManager.GetString("Settings_Section_Tts", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TTS 引擎 的本地化字符串。
        /// </summary>
        public static string Settings_TtsEngineLabel {
            get {
                return ResourceManager.GetString("Settings_TtsEngineLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edge TTS（在线） 的本地化字符串。
        /// </summary>
        public static string Settings_TtsEngine_Edge {
            get {
                return ResourceManager.GetString("Settings_TtsEngine_Edge", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Piper TTS（离线） 的本地化字符串。
        /// </summary>
        public static string Settings_TtsEngine_Piper {
            get {
                return ResourceManager.GetString("Settings_TtsEngine_Piper", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edge 音色 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoiceLabel {
            get {
                return ResourceManager.GetString("Settings_EdgeVoiceLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-US-AriaNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_AriaNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_AriaNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-US-GuyNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_GuyNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_GuyNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-GB-SoniaNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_SoniaNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_SoniaNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-US-EmmaMultilingualNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_EmmaMultilingualNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_EmmaMultilingualNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-US-JennyNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_JennyNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_JennyNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-GB-RyanNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_RyanNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_RyanNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 en-AU-NatashaNeural 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoice_NatashaNeural {
            get {
                return ResourceManager.GetString("Settings_EdgeVoice_NatashaNeural", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edge 语速 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeRateLabel {
            get {
                return ResourceManager.GetString("Settings_EdgeRateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 +0% 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeRateDefault {
            get {
                return ResourceManager.GetString("Settings_EdgeRateDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Piper 可执行文件路径（piper.exe） 的本地化字符串。
        /// </summary>
        public static string Settings_PiperExecutableLabel {
            get {
                return ResourceManager.GetString("Settings_PiperExecutableLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Piper 模型路径（.onnx） 的本地化字符串。
        /// </summary>
        public static string Settings_PiperModelLabel {
            get {
                return ResourceManager.GetString("Settings_PiperModelLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试朗读文本 的本地化字符串。
        /// </summary>
        public static string Settings_TestTextLabel {
            get {
                return ResourceManager.GetString("Settings_TestTextLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Seeds of stories, brought by the wind and cultivated by time. 的本地化字符串。
        /// </summary>
        public static string Settings_TestTextDefault {
            get {
                return ResourceManager.GetString("Settings_TestTextDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试语音 的本地化字符串。
        /// </summary>
        public static string Settings_TestTtsButton {
            get {
                return ResourceManager.GetString("Settings_TestTtsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TTS 引擎 的本地化字符串。
        /// </summary>
        public static string Settings_TtsEngineHeader {
            get {
                return ResourceManager.GetString("Settings_TtsEngineHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edge 音色 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeVoiceHeader {
            get {
                return ResourceManager.GetString("Settings_EdgeVoiceHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Edge 语速 的本地化字符串。
        /// </summary>
        public static string Settings_EdgeRateHeader {
            get {
                return ResourceManager.GetString("Settings_EdgeRateHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Piper 可执行文件 的本地化字符串。
        /// </summary>
        public static string Settings_PiperExecutableHeader {
            get {
                return ResourceManager.GetString("Settings_PiperExecutableHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Piper 模型路径 的本地化字符串。
        /// </summary>
        public static string Settings_PiperModelHeader {
            get {
                return ResourceManager.GetString("Settings_PiperModelHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试朗读文本 的本地化字符串。
        /// </summary>
        public static string Settings_TestTtsHeader {
            get {
                return ResourceManager.GetString("Settings_TestTtsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        public static string Settings_SaveButton {
            get {
                return ResourceManager.GetString("Settings_SaveButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除 TTS 缓存 的本地化字符串。
        /// </summary>
        public static string Settings_ClearCacheButton {
            get {
                return ResourceManager.GetString("Settings_ClearCacheButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择 ECDICT 数据文件 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_EcDictTitle {
            get {
                return ResourceManager.GetString("Settings_Dialog_EcDictTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 CSV 文件|*.csv|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_CsvFilter {
            get {
                return ResourceManager.GetString("Settings_Dialog_CsvFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择 MDict 词典文件 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_MDictTitle {
            get {
                return ResourceManager.GetString("Settings_Dialog_MDictTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 词典|*.mdx|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_MDictFilter {
            get {
                return ResourceManager.GetString("Settings_Dialog_MDictFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择 MDict 资源包（可选） 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_MDictResourceTitle {
            get {
                return ResourceManager.GetString("Settings_Dialog_MDictResourceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 MDict 资源包|*.mdd|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_MDictResourceFilter {
            get {
                return ResourceManager.GetString("Settings_Dialog_MDictResourceFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择 Piper 可执行文件 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_PiperExecutableTitle {
            get {
                return ResourceManager.GetString("Settings_Dialog_PiperExecutableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 可执行文件|*.exe|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_ExeFilter {
            get {
                return ResourceManager.GetString("Settings_Dialog_ExeFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择 Piper 语音模型 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_PiperModelTitle {
            get {
                return ResourceManager.GetString("Settings_Dialog_PiperModelTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ONNX 模型|*.onnx|所有文件|*.* 的本地化字符串。
        /// </summary>
        public static string Settings_Dialog_OnnxFilter {
            get {
                return ResourceManager.GetString("Settings_Dialog_OnnxFilter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置已保存。 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccess {
            get {
                return ResourceManager.GetString("Message_SaveSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置已保存，但检测到以下问题：{0} 的本地化字符串。
        /// </summary>
        public static string Message_SaveSuccessWithWarning_Format {
            get {
                return ResourceManager.GetString("Message_SaveSuccessWithWarning_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存失败：{0} 的本地化字符串。
        /// </summary>
        public static string Message_SaveFailed_Format {
            get {
                return ResourceManager.GetString("Message_SaveFailed_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TTS 服务尚未初始化 的本地化字符串。
        /// </summary>
        public static string Message_TtsServiceNotReady {
            get {
                return ResourceManager.GetString("Message_TtsServiceNotReady", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试文本不能为空 的本地化字符串。
        /// </summary>
        public static string Message_TtsTestTextEmpty {
            get {
                return ResourceManager.GetString("Message_TtsTestTextEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 朗读失败：{0} 的本地化字符串。
        /// </summary>
        public static string Message_TtsTestFailed_Format {
            get {
                return ResourceManager.GetString("Message_TtsTestFailed_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TTS 缓存已清除。 的本地化字符串。
        /// </summary>
        public static string Message_CacheCleared {
            get {
                return ResourceManager.GetString("Message_CacheCleared", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂无 TTS 缓存。 的本地化字符串。
        /// </summary>
        public static string Message_NoCache {
            get {
                return ResourceManager.GetString("Message_NoCache", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除缓存失败：{0} 的本地化字符串。
        /// </summary>
        public static string Message_ClearCacheFailed_Format {
            get {
                return ResourceManager.GetString("Message_ClearCacheFailed_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECDICT 文件不存在。 的本地化字符串。
        /// </summary>
        public static string Message_ValidateEcDictNotFound {
            get {
                return ResourceManager.GetString("Message_ValidateEcDictNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MDict 词典文件不存在。 的本地化字符串。
        /// </summary>
        public static string Message_ValidateMDictNotFound {
            get {
                return ResourceManager.GetString("Message_ValidateMDictNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MDict 资源包不存在。 的本地化字符串。
        /// </summary>
        public static string Message_ValidateMDictResourceNotFound {
            get {
                return ResourceManager.GetString("Message_ValidateMDictResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piper 可执行文件路径无效。 的本地化字符串。
        /// </summary>
        public static string Message_ValidatePiperExecutableInvalid {
            get {
                return ResourceManager.GetString("Message_ValidatePiperExecutableInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piper 模型路径无效。 的本地化字符串。
        /// </summary>
        public static string Message_ValidatePiperModelInvalid {
            get {
                return ResourceManager.GetString("Message_ValidatePiperModelInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickDict 查词 的本地化字符串。
        /// </summary>
        public static string Plugin_DisplayName {
            get {
                return ResourceManager.GetString("Plugin_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开 QuickDict 英语单词查询窗口 的本地化字符串。
        /// </summary>
        public static string Plugin_Description {
            get {
                return ResourceManager.GetString("Plugin_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查词 的本地化字符串。
        /// </summary>
        public static string ToolbarButton_Label {
            get {
                return ResourceManager.GetString("ToolbarButton_Label", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 QuickDict 的本地化字符串。
        /// </summary>
        public static string ToolbarButton_FallbackText {
            get {
                return ResourceManager.GetString("ToolbarButton_FallbackText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未找到可用的词典文件。请在 QuickDict 设置中配置 ECDICT（ecdict.csv）或 MDict（.mdx）路径。 的本地化字符串。
        /// </summary>
        public static string Message_DictionaryUnavailable {
            get {
                return ResourceManager.GetString("Message_DictionaryUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 已初始化 的本地化字符串。
        /// </summary>
        public static string Message_PluginInitialized_Format {
            get {
                return ResourceManager.GetString("Message_PluginInitialized_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 已关闭 的本地化字符串。
        /// </summary>
        public static string Message_PluginShutdown_Format {
            get {
                return ResourceManager.GetString("Message_PluginShutdown_Format", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 加载 QuickDict 设置失败，已使用默认设置 的本地化字符串。
        /// </summary>
        public static string Message_LoadSettingsFailed {
            get {
                return ResourceManager.GetString("Message_LoadSettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 初始化 QuickDict 服务失败 的本地化字符串。
        /// </summary>
        public static string Message_InitializeServicesFailed {
            get {
                return ResourceManager.GetString("Message_InitializeServicesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 初始化 QuickDict 设置面板失败 的本地化字符串。
        /// </summary>
        public static string Message_InitializeSettingsViewFailed {
            get {
                return ResourceManager.GetString("Message_InitializeSettingsViewFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 注册 QuickDict 工具栏按钮失败 的本地化字符串。
        /// </summary>
        public static string Message_RegisterToolbarItemFailed {
            get {
                return ResourceManager.GetString("Message_RegisterToolbarItemFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 QuickDict 词典加载任务时出错 的本地化字符串。
        /// </summary>
        public static string Message_CancelDictionaryLoadFailed {
            get {
                return ResourceManager.GetString("Message_CancelDictionaryLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 关闭 QuickDict TTS 服务时出错 的本地化字符串。
        /// </summary>
        public static string Message_DisposeTtsServiceFailed {
            get {
                return ResourceManager.GetString("Message_DisposeTtsServiceFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 QuickDict 词典加载已取消（可能已超时）。 的本地化字符串。
        /// </summary>
        public static string Message_DictionaryLoadCanceled {
            get {
                return ResourceManager.GetString("Message_DictionaryLoadCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 后台加载 QuickDict 词典数据时出错 的本地化字符串。
        /// </summary>
        public static string Message_LoadDictionaryFailed {
            get {
                return ResourceManager.GetString("Message_LoadDictionaryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 QuickDict 词典可用性时出错 的本地化字符串。
        /// </summary>
        public static string Message_CheckDictionaryAvailabilityFailed {
            get {
                return ResourceManager.GetString("Message_CheckDictionaryAvailabilityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuickDict 设置已保存；词典/TTS 路径变更需重启插件后生效。 的本地化字符串。
        /// </summary>
        public static string Message_SettingsSavedRestartRequired {
            get {
                return ResourceManager.GetString("Message_SettingsSavedRestartRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 构造 QuickDict 工具栏按钮视图失败 的本地化字符串。
        /// </summary>
        public static string Message_CreateToolbarButtonFailed {
            get {
                return ResourceManager.GetString("Message_CreateToolbarButtonFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开 QuickDict 查词窗口失败 的本地化字符串。
        /// </summary>
        public static string Message_OpenDictionaryWindowFailed {
            get {
                return ResourceManager.GetString("Message_OpenDictionaryWindowFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 初始化 QuickDict 主题资源失败 的本地化字符串。
        /// </summary>
        public static string Message_InitializeThemeResourcesFailed {
            get {
                return ResourceManager.GetString("Message_InitializeThemeResourcesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清理 QuickDict 主题资源时出错 的本地化字符串。
        /// </summary>
        public static string Message_ShutdownThemeResourcesFailed {
            get {
                return ResourceManager.GetString("Message_ShutdownThemeResourcesFailed", resourceCulture);
            }
        }
    }
}
